### ISSUE TITLE
A little documentation would be nice.

### ISSUE THREAD

**Issue by stuphi** [pimoroni/scroll-phat#1]
Just trying to get me scroll pHat working and getting the following error.
pi@raspberrypi:~/dev/scroll-phat $ python test-all.py 
Traceback (most recent call last):
  File "test-all.py", line 3, in <module>
    import scrollphat
  File "/home/pi/dev/scroll-phat/scrollphat.py", line 6, in <module>
    bus = smbus.SMBus(1)
IOError: [Errno 2] No such file or directory

I will continue poking around, but it would be nice if it was not quite so dark in this corner :-)

**Comment by stuphi** [comment]
Sorted. Extra documentation much appreciated

**Comment by Wandelation** [comment]
Would you mind sharing what you found? I'm having the same issue.

**Comment by stuphi** [comment]
I can't remember the details, but I do remember that the documentation was updated to reflect what I needed to do, so I didn't comment on it here. Looking back through the commits, on Nov 29th, this was added to the documentation `sudo apt-get install python-smbus`
Give that a try.

**Comment by Wandelation** [comment]
I had python-smbus installed already. I managed to sort it out myself eventually, I think what did the trick was running raspi-config and going into Advanced settings and enabling I2C (and rebooting). Also possible that rebooting was the thing that did it.
