### ISSUE TITLE
Flip font

### ISSUE THREAD

**Issue by alexellis** [pimoroni/scroll-phat#16]
I was going to have a look at optionally flipping the font because the HAT + PI would probably self-balance better if upside down with cables etc coming out the top. Where you would suggest starting?

Would an image rotate and flip transform work in the load_font method?

**Comment by Gadgetoid** [comment]
This is something I'd probably do at a much lower level- IE: look at rotating the whole buffer right before the data is written out to the LED driver, that way everything you draw will be flipped too.

This was definitely a feature on my TODO list.

**Comment by ncguk** [comment]
+1 for this request – using the right-angle header supplied with the Scroll pHAT kit means the pHAT naturally sits upside-down when vertical, so the ability to rotate the text/display would be very useful.

**Comment by stuphi** [comment]
I have had a bash at this. See https://github.com/pimoroni/scroll-phat/pull/19

**Comment by stuphi** [comment]
I think this is now sorted with https://github.com/pimoroni/scroll-phat/pull/21

**Comment by RadioactiveMouse** [comment]
Doesn't seem to be working for me. I have the right angled headers and the scrollhat working together and stands up like a charm but running simple-text-scroll-rotated.py still reads the text the same as the normal version. Am I missing something?

**Comment by stuphi** [comment]
Hi.Have you run setup.py since downloading the new version?

**Comment by jtbutcher** [comment]
@RadioactiveMouse using the setup script in the readme ( curl -sSL get.pimoroni.com/scrollphat | bash ) doesn't update the library. To get it to work I did the following:

I used the Pimoroni directory that was created for the examples to keep things reasonably tridy

$ cd Pimoroni 
$ git clone https://github.com/pimoroni/scroll-phat
$ cd scroll-phat/library
$ sudo setup.py install

adding 

scrollphat.rotate = True

to your script or running simple-text-scroll-rotated.py should work

**Comment by RadioactiveMouse** [comment]
Thanks @jtbutcher that got it working. Bit tricky to update the library file!

Any chance this could be fixed to update with the script in the readme? Having to checkout the repo etc is a pain.

**Comment by mentazm** [comment]
The rotate script doesn't rotate for me, it just plays it the normal way up and terminal reads 'io error' every so often. Any ideas whats up?

**Comment by stuphi** [comment]
Have you tried he suggestion above? Basically you need to make sure the lib gets re-built and installed.

**Comment by mentazm** [comment]
Just done that and working now, thanks. I am now trying to merge the twython script below with the rotated script to get it to print a real time feed of my twitter feed and have no idea what I'm doing. I'm a total python beginner, and have very limited programming knowledge from 20 years ago.

Any ideas how to go about merging the two scripts?

===

from twython import TwythonStreamer

#auth tokens here

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            print data['user', 'text'].encode('utf-8')
 
    def on_error(self, status_code, data):
        print status_code, data
 
stream = MyStreamer(APP_KEY, APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

stream.user()

**Comment by alexellis** [comment]
Closing issue as this was resolved by Pull Request. Thanks all.
