### ISSUE TITLE
Font.img not found

### ISSUE THREAD

**Issue by tombomb12** [pimoroni/scroll-phat#17]
so when i run the example files from idle 2.7 it comes back with 2 errors here is a screen shot please could someone tell me how to fix it.
![screen shot 2015-12-16 at 21 31 01](https://cloud.githubusercontent.com/assets/16327608/11854534/6549a016-a43c-11e5-889a-07f5c686aa24.png)

**Comment by Gadgetoid** [comment]
Copy the file font.png from here: https://raw.githubusercontent.com/pimoroni/scroll-phat/master/library/font.png  into the `/home/pi/Pimoroni/scrollhat/` directory.

I need to look into this!

**Comment by Gadgetoid** [comment]
In fact, try this: `sudo pip install --upgrade scrollphat`

**Comment by tombomb12** [comment]
Thank you so much moving the font.png file there has got it working thanks a lot.

**Comment by Gadgetoid** [comment]
I think the font.png and dependency upon PIL are troublesome enough that in the next release we'll bake the font into the code as a byte array and provide a tool for converting font.png images into usable fonts.

**Comment by Gadgetoid** [comment]
I've pushed up a new version of the library to git which includes a pre-baked version of font.png- font.py. This lives inside a new scrollphat "package" to keep everything together.

You can replace the pre-baked font using the set-font method and I've moved the old load_font method into a mkfont.py in tools, which will allow you to modify the original font.png and bake your own like so:

`python mkfont.py > my_font.py`

Then then load it:

```python
from my_font.py import font as my_font

scrollphat.load_font(my_font)
```

This means no more PIL as a dependency. Yay!

**Comment by RogueM** [comment]
:zap:
