### ISSUE TITLE
Error during install (python3-pip)

### ISSUE THREAD

**Issue by realies** [pimoroni/scroll-phat#22]
Just installed the latest jessie lite, did update and upgrade and on install (curl -sSL get.pimoroni.com/scrollphat | bash) I found myself stuck after:

Sorry, Apt failed to install python3-pip, I can't continue!

sudo apt-get -f install seemed to fix it by installing libpython3.4-dev

**Comment by RogueM** [comment]
it must have been a glitch as I've just tried with a clean SD / Jessie Lite and libpython3.4-dev was successfully pulled from the repo and installed, in turn allowing python3-pip to follow.

**Comment by alexellis** [comment]
@realies sounds like the issue may be fixed now. Can you close the issue?

**Comment by alexellis** [comment]
@RogueM ping

**Comment by RogueM** [comment]
Don't have such power, I'm just a minion!
@Gadgetoid ping

**Comment by alexellis** [comment]
I meant to ping @realies ... who opened the issue, sorry :) @realies if you're good now, can you close the issue?

**Comment by realies** [comment]
Sorry for the late pong... :)
