### ISSUE TITLE
sine example split request

### ISSUE THREAD

**Issue by AndiCui** [pimoroni/scroll-phat#25]
the sine.py shows IP address and CPU usage, because the second WHILE loop won’t be run.
I suggest to rename the example and spilt it to two example files.

**Comment by Gadgetoid** [comment]
You're right, it should be chopped up. It was actually just a test when we were originally writing the code, but I think it's probably still useful stuff for people so I'll fix it!

**Comment by Gadgetoid** [comment]
Fixed in df3e851bf5fb737d5ff7c45731d9f2c81a45f75d

**Comment by AndiCui** [comment]
Thanks @Gadgetoid
