### ISSUE TITLE
auto scroll request

### ISSUE THREAD

**Issue by AndiCui** [pimoroni/scroll-phat#26]
Plz consider adding a auto_scroll variable or a .scroll_string function that pass the message for one time automatically.

**Comment by Gadgetoid** [comment]
Duly considered- this is something I'd agree with, since it's perhaps the most common use-case, but I'm not yet sure how it'll be implemented since it may necessitate threading and... oh boy I hate threading in Python!

**Comment by AndiCui** [comment]
There should be a code in the sense hat library does basically the same job. Haven't looked up yet..

**Comment by Gadgetoid** [comment]
From what I can tell, the Sense HAT scroll is synchronous? This may not necessarily be a bad choice, since the threading could be left to the discretion of the user and keep the library simple.

Perhaps a `scroll_message("some text")` method would fit this bill- a blocking method that scrolls the given message once ( or a number of times ). Something that fits, loosely, this definition:

```python
scroll_message(text,
    speed=100,
    repeat=0)
```

**Comment by alexellis** [comment]
What is the use-case for the auto-scroll? I would be tempted to write an example rather than editing the core library, so people can manage the threading themselves.

**Comment by AndiCui** [comment]
@alexellis I think this will make the code of a lot of use cases less cluttered.

**Comment by Gadgetoid** [comment]
I've created a branch with some auto-scroll functionality. It's a little ugly, but it works. I've tried to cover the basic use-cases without getting too spaghetti.

https://github.com/pimoroni/scroll-phat/tree/auto_scroll

Included are two demos:

* many-scroll.py - Iterates through and displays an array of text strings ( the numbers one to ten in this case ) using auto-scroll functionality, and `scrollphat.busy()` to wait for completion.
* auto-scroll.py - A copy of simple-text-scroll.py which uses the auto-scroll functionality and accepts an additional argument "repeat" which dictates how many times the scrolling message will be repeated.

**Comment by AndiCui** [comment]
@Gadgetoid Sry being pretty inactive. 
Did you say ugly? No, thats ugly > https://github.com/AndiCui/SLX2016

**Comment by Gadgetoid** [comment]
Today I learned that GPIO.setup accepts a tuple...

**Comment by Gadgetoid** [comment]
Shelving this for the time being, I think it's possibly something best implemented on a case-by-case basis.

**Comment by apjavel** [comment]
I think the auto scroll branch is absolutely brilliant! It was the missing piece for my use case. Please consider Adding it to the main branch. Cheers
