### ISSUE TITLE
Needs re-boot after install to work.

### ISSUE THREAD

**Issue by quietbiker** [pimoroni/scroll-phat#33]
Just got this up and running.  I've suggest tweaking the instructions to include that a Reboot is required.
I guess this may not be needed if I2C was previously enabled, but on a new Pi Zero (fresh, updated image) I did need to re-boot.  Some users may need a hand.

Also it may help newbies to know they need to navigate to the python scripts and how to run them;

cd Pimorino/scrollphat/
python ip.py

(etc).

A nice big of work - well done :-)

**Comment by AndiCui** [comment]
@quietbiker nice that you pointed that out. It is really quite strange to provide a detailed instruction on installing but not using.

**Comment by RogueM** [comment]
I can't see why we couldn't end the scripts with some usage guidance...

... the reboot requirements are already stated in red as changes are made where appropriate and eventually will be a prompt at the end, similar to how raps-config suggests reboot, but it's not as simple as it sounds as i2c and isp setup are child processes.
