### ISSUE TITLE
simple-text-scroll-(rotated).py

### ISSUE THREAD

**Issue by mamvcivm** [pimoroni/scroll-phat#36]
Hi there, newbie here, so apologies upfront!
I can successfully run most of the scroll-phat examples, but not the text scroll ones. When I run them, i get no output on the scroll-phat - are they waiting for me to enter some text? 

If so, if I enter (eg) Hello World, I get the following error:-
usage: python simple-text-scroll-rotated.py "message"
press CTRL-C to exit

>>> hello world
SyntaxError: invalid syntax
>>> hello
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    hello
NameError: name 'hello' is not defined
>>>
KeyboardInterrupt

If I then enter "Hello World" ie with quotation marks I get:-

>>> ================================ RESTART ================================
>>>

usage: python simple-text-scroll-rotated.py "message"
press CTRL-C to exit

>>> "hello world"
'hello world'
>>>

But still no output on the Scroll-Phat itself...

Can anyone suggest what I'm doing wrong?

Thanks

**Comment by AndiCui** [comment]
If you have a space, the code will interpret it as 2 arguments and refuse to run.
Whenever you write a special character, try put a backslash before it

**Comment by alexellisadp** [comment]
This is what I do...

```
[pi@raspberry] $ sudo python simple-text-scroll-rotated.py "The weather is very sunny"
```

Can you try that and let us know what you get?

**Comment by mamvcivm** [comment]
Marvellous :-) That worked a treat! - 

So, why won't it work from within IDLE 2 or 3?

Thanks

Thanks

**Comment by alexellis** [comment]
Glad it works. I2c needed for the screen needs sudo access. Are you running idle as sudo? 

If it now works fine are OK to close the issue?

Alex

**Comment by AndiCui** [comment]
@alexellis I do remember that I ran it more than once secesfully without sudo. It that only in Jessie?

**Comment by mamvcivm** [comment]
Thanks Alexellis, can you just ellaborate a little? How come some of the example scripts will run in IDLE but others won't? Basically, all the scripts will run in IDLE except the two simple-text-scroll ones...

Andy
