### ISSUE TITLE
Weirdness with scrollphat.graph()

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/scroll-phat#47]
I'm seeing odd behaviour when passing a list of integer values rather than floats. With ints, all of the columns seem to scale to the max. If you convert the ints to floats, it behaves as expected.

**Comment by alexellis** [comment]
Hi @sandyjmacdonald Have you got an example I could try out?

**Comment by sandyjmacdonald** [comment]
Something simple like:

```
import scrollphat as sp
sp.graph([1,2,3,4,5,6,7,8,9,10,11])
```

**Comment by Gadgetoid** [comment]
This is old, dead code that should probably be deleted and replaced with a succinct example. The file `scrollphat.py` shouldn't exist anymore. This puzzled me for at least 10 minutes when my changes weren't getting picked up. Doh!

**Comment by Gadgetoid** [comment]
Ah, although the `graph` method still exists in ISblahblahblah.py.
