### ISSUE TITLE
'turn-leds-off.py' not working.

### ISSUE THREAD

**Issue by RyanT95** [pimoroni/scroll-phat#49]
Just got my Pi Zero with the Scroll PHat, everything installed fine and I ran a few of the example scripts. But when I execute the 'turn-leds-off.py' script nothing happens. With Some of the examples the LEDs turn off for a fraction of a second, but they turn back on and the example carries on running, just flashing the LEDs off and on in effect.

Please help, I have to reboot every time I want to turn the LEDs off.

Cheers.

**Comment by alexellis** [comment]
Hi @RyanT95 I'm fairly sure this script worked for me when I ran it a couple of days ago. You may want to get in touch with the Pimoroni tech support through https://shop.pimoroni.com/pages/contact-us

Are you running on Raspbian and did you use the `curl | sh` installation from the homepage?

**Comment by AndiCui** [comment]
Sounds like a chip error to me

**Comment by RyanT95** [comment]
Hi @alexellis Yeah, I'm running Raspbian and I installed using the instructions from the pimoroni/scroll-phat github page.

**Comment by alexellis** [comment]
@RyanT95 probably something not quite right on the hardware/connections side then. I'm sure the guys will help you if you ping them through their support page.
