### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by robertclarkson** [pimoroni/scroll-phat#60]
Hey guys, 

Great little display! I was trying to figure out how to change the font. I can see there is a font.png in the repo, and i have changed this, but can't figure out where it is stored in the pi system, and have done a find to look for it, and still no luck. Does this PNG get converted into something else?

Cheers
Rob

**Comment by AndiCui** [comment]
You need to run mkfont.py in tools/ and replace the font.py in the library. You will have to reinstall the lib

**Comment by AndiCui** [comment]
@robertclarkson haven’t see you replying. Did it work?

**Comment by robertclarkson** [comment]
@AndiCui Thanks for this answer, i haven't had time to test it yet. It sounds like it will work
