### ISSUE TITLE
Updates for Docker integration.

### ISSUE THREAD

**Issue by alexellis** [pimoroni/scroll-phat#66]
I'm looking at the following (work in progress):

* Remove all comments from Dockerfile (the docker.md file is enough, will be renamed readme.md)
* Refactor the Dockerfile to make it a single layer and easier to pull/extract on the Zero.
* Make mention of i2c on host in readme.md

Re comment by @dfranssen to include all dependencies for examples in Dockerfile I don't think this approach is ideal. The Dockerfile should be lean and these can be added separately later. The examples already have good checking for libraries present.

Adding a library is normally as simple as something like:

```
FROM alexellis2/scroll-phat
RUN pip install numpy
```

I would still like to promote the Dockerfile to the top level of the repo to make it easier to use and less surprising. Check out a few open source projects (you'll see that's where the file sits)

@RogueM @Gadgetoid anything else?

**Comment by Gadgetoid** [comment]
I don't see any issue with moving the Dockerfile to the top of the repo. While I'd like to keep it uncluttered, if it genuinely makes it easier to use then the benefits outweigh the drawbacks. What do you think @RogueM?

**Comment by alexellis** [comment]
I'm expecting to generate interest in Pimoroni products from a Pi Zero Blinkt workshop at Dockercon in April, it would be the least surprising experience to have some Dockerfiles around in the root of popular repositories. I've also covered: mote-phat, blinkt and scroll-phat.

**Comment by RogueM** [comment]
I'm not familiar woth the process, but I don't see the advantage... can someone spell it out for me?

**Comment by alexellis** [comment]
The Docker-workflow is: `git clone https://github.com/org/project-a ; cd project-a; docker build -t project-a .`

* Putting the Dockerfile anywhere else but the root means having to search for it, which makes it look like one doesn't exist and is non-standard.

* The Dockerfile needs to be at the root of the repository because ../ or ../../ etc relative references are not supported, only from the current level downwards.

To work around this I have to use a script to copy the Dockerfile from a temporary location to the root, do a build and then delete it, but is a hack and relies on breaking the pattern. It is similar to a Makefile, but without the ../ relative paths breaks when moved around.

Multiple Dockerfiles are supported, but are only used in exotic builds.

**Comment by alexellis** [comment]
@RogueM

**Comment by RogueM** [comment]
yes, I read you the first time :)

... my opinion is that it's 6 of one, half a dozen of the other. The subfolder has the benefit of a dedicated README where you can be as verbose as you'd like, as well as matching my preference of keeping the repo root dir clean.

but I have no write access to the repo in any case, so even if I was of the opinion it needs to be reorganised as you suggest I couldn't do it - you need to convince @Gadgetoid, not me (I was only replying since he asked my opinion).
