### ISSUE TITLE
Error when importing scrollphat

### ISSUE THREAD

**Issue by neocotic** [pimoroni/scroll-phat#70]
I just received my Raspberry Pi Zero W Scroll Bot project and got everything setup, however, I'm getting a problem when trying to run any of the examples or simply the `scrollphat` module at all:

``` bash
pi@raspberrypi:~/Pimoroni/scrollphat $ python -c "import scrollphat"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/scrollphat/__init__.py", line 20, in <module>
    controller = IS31FL3730(smbus, font)
  File "/usr/lib/python2.7/dist-packages/scrollphat/IS31FL3730.py", line 21, in __init__
    self.set_mode(self.i2cConstants.MODE_5X11)
  File "/usr/lib/python2.7/dist-packages/scrollphat/IS31FL3730.py", line 62, in set_mode
    self.bus.write_i2c_block_data(self.i2cConstants.I2C_ADDR, self.i2cConstants.CMD_SET_MODE, [self.i2cConstants.MODE_5X11])
IOError: [Errno 5] Input/output error
pi@raspberrypi:~/Pimoroni/scrollphat $ python3 -c "import scrollphat"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/scrollphat/__init__.py", line 20, in <module>
    controller = IS31FL3730(smbus, font)
  File "/usr/lib/python3/dist-packages/scrollphat/IS31FL3730.py", line 21, in __init__
    self.set_mode(self.i2cConstants.MODE_5X11)
  File "/usr/lib/python3/dist-packages/scrollphat/IS31FL3730.py", line 62, in set_mode
    self.bus.write_i2c_block_data(self.i2cConstants.I2C_ADDR, self.i2cConstants.CMD_SET_MODE, [self.i2cConstants.MODE_5X11])
OSError: [Errno 5] Input/output error
```

I've checked and I2C is enabled but, I'll admit, this was the first time that I've soldered on a circuit, so I'm not sure if it's gone wrong there. The solder joints look good to me though. Any input on this error or advice as to whether it could be related to bad soldering would be greatly appreciated. Is it possible to diagnose the GPIO connection to test that it's all good or, even better, detect any errors on individual connections?

----

Again, I'll admit this is my first time really working with GPIO so please excuse my ignorance, but here's the output of running `i2cdetect` in case it helps at all:

``` bash
pi@raspberrypi:~/Pimoroni/scrollphat $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- 74 -- -- --
```

**Comment by neocotic** [comment]
Doh! I just realised that the kit came with a Scroll pHAT HD not a Scroll pHAT. I'm going to install [scroll-phat-hd](https://github.com/pimoroni/scroll-phat-hd) now and, if I run into any more problems, I'll raise an issue over there or in the forums.

**Comment by alexellis** [comment]
Wow, I'm behind here.. there's actually a Scroll pHAT HD now? 💯

**Comment by neocotic** [comment]
17x7 as opposed to 11x5.

For anyone interested, I managed to get it all working with the correct `scrollphathd` module. Panic over (for me)! I thought I'd really messed up the soldering.
