### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by Tom-Archer** [pimoroni/scroll-phat#73]
Trying to get scrollphat up and running (on the AIY image) using both the Pimoroni dashboard and the Bash script, but whilst both work in Python2, when attempting to run in Python3 I received, `ImportError: No module named 'scrollphat'`. To get it working under Python3, I had to clone the repo and do, `sudo python3 setup.py install`. Not sure if this is a weird issue with the AIY image, or a general issue.

**Comment by RogueM** [comment]
what version of Python 3 is that running?

**Comment by Tom-Archer** [comment]
Python 3.4.2 I believe.
