### ISSUE TITLE
import scrollphat error

### ISSUE THREAD

**Issue by daveyman123** [pimoroni/scroll-phat#74]
I am getting an error for both python3 and python2 with raspberry pi 0 and 3

I have tried installing from the git repo and enabled i2c.

i2c doesnt put out anything that is out of the ordinary

I am on retropie. I have tried it on multiple versions of retropie.

the one liner bash script doesnt work. I tried that first.

I am trying to use a scrollphat.

Here is the error:

```
Traceback (most recent call last):
  File "test-graph.py", line 5, in <module>
    import scrollphat
  File "/usr/lib/python3/dist-packages/scrollphat/__init__.py", line 20, in <module>
    controller = IS31FL3730(smbus, font)
  File "/usr/lib/python3/dist-packages/scrollphat/IS31FL3730.py", line 21, in __init__
    self.set_mode(self.i2cConstants.MODE_5X11)
  File "/usr/lib/python3/dist-packages/scrollphat/IS31FL3730.py", line 62, in set_mode
    self.bus.write_i2c_block_data(self.i2cConstants.I2C_ADDR, self.i2cConstants.CMD_SET_MODE, [self.i2cConstants.MODE_5X11])
OSError: [Errno 5] Input/output error
```

**Comment by Gadgetoid** [comment]
This is the very first command that the library attempts to send to the Scroll pHAT. Could you post a picture of your soldering?

**Comment by dglaude** [comment]
I would try from the command line this:

> i2cdetect -y 1

This is basic troubleshooting of the I2C level part.

[Pinout.xyz say you should find the IS31FL3730 at address 0x60](https://pinout.xyz/pinout/scroll_phat)
