### ISSUE TITLE
Docker example fails

### ISSUE THREAD

**Issue by petehalverson** [pimoroni/scroll-phat#79]
Followed the example defined in https://github.com/pimoroni/scroll-phat/tree/master/docker

```
$ docker run -ti --privileged scroll-phat

Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scrollphat
>>> scrollphat.set_pixel(1,1,True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/scrollphat/__init__.py", line 145, in set_pixel
  File "build/bdist.linux-armv7l/egg/scrollphat/__init__.py", line 26, in _get_controller
  File "build/bdist.linux-armv7l/egg/scrollphat/IS31FL3730.py", line 17, in __init__
IOError: [Errno 2] No such file or directory
```

**Comment by petehalverson** [comment]
Sorry. This may have been obvious to experienced Raspberry Pi users, i2c was not enabled:

```
$ ls /dev/i2c*
ls: cannot access /dev/i2c*: No such file or directory
```

I realize @alexellis made reference to it [lower down in the readme](https://github.com/pimoroni/scroll-phat/tree/master/docker#deployment-use-case), but I'd suggest making a note of it by the REPL example.

Also, I'd advocate moving the Dockerfile to the root of the repo...seems odd to have such a workaround. I would be happy to submit a PR for that.

Thanks! Really love the scroll-phat and the using it with Docker!

**Comment by Gadgetoid** [comment]
> Also, I'd advocate moving the Dockerfile to the root of the repo...seems odd to have such a workaround. I would be happy to submit a PR for that.

This useful feedback. @alexellis was also keen to have the Dockerfile in the root of the repo, but we were somewhat resistant to clutter. If it's a necessary and accepted practise, then we should probably stick with it across all of our repositories.

**Comment by alexellis** [comment]
Yay, please move it up to the root 👍
