### ISSUE TITLE
"apt upgrade" fails, conflicts with python3-scrollphatd_1.1.0

### ISSUE THREAD

**Issue by dangu** [pimoroni/scroll-phat#81]
Hello

I am trying to upgrade my Raspberry Pi 3 B but I got stuck with the following error message:

pi@raspberrypi:~ $ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  python3-scrollphathd
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
38 not fully installed or removed.
Need to get 0 B/18.0 kB of archives.
After this operation, 14.3 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Reading changelogs... Done
(Reading database ... 122984 files and directories currently installed.)
Preparing to unpack .../python3-scrollphathd_1.1.0_all.deb ...
Unpacking python3-scrollphathd (1.1.0) over (1.0.1) ...
dpkg: error processing archive /var/cache/apt/archives/python3-scrollphathd_1.1.0_all.deb (--unpack):
 trying to overwrite '/usr/bin/scrollphathd_api', which is also in package python-scrollphathd 1.1.0
Errors were encountered while processing:
 /var/cache/apt/archives/python3-scrollphathd_1.1.0_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

My version:
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

**Comment by Gadgetoid** [comment]
This was actually an issue with Scroll pHAT HD: https://github.com/pimoroni/scroll-phat-hd

And it has been fixed by version 1.1.1 - https://github.com/pimoroni/scroll-phat-hd/commit/974ad9fbd7e303b4ccf78fb05154e4d524417dc8

An `apt update && apt update` should work now.
