### ISSUE TITLE
Example ukweather.py - incorrect RSS feed URL

### ISSUE THREAD

**Issue by 75andyd** [pimoroni/scroll-phat#82]
Hi, looks like the BBC Weather RSS feed has changed:
<https://www.bbc.com/weather/about/17543675>
Example:
<https://weather-broker-cdn.api.bbci.co.uk/en/forecast/rss/3day/s2>
Changed line 31 to:
`url = "https://weather-broker-cdn.api.bbci.co.uk/en/forecast/rss/3day/" + postcode`
and all is good

**Comment by Gadgetoid** [comment]
Thank you for letting me know! Should hopefully be fixed.
