### ISSUE TITLE
localweather.py : discontinued yahooapis & error message

### ISSUE THREAD

**Issue by eskiiom** [pimoroni/scroll-phat#84]
Hello,

I am trying to use localweather.py but I have an error message.

`Location: Le Vésinet, FR
Traceback (most recent call last):
  File "localweather.py", line 68, in <module>
    weather = get_weather(location_string)
  File "localweather.py", line 41, in get_weather
    uri = base + encode(qs)
  File "localweather.py", line 33, in encode
    val = urllib.parse.urlencode(qs).replace("+", "%20")
AttributeError: 'module' object has no attribute 'parse'
`

At first I was thinking the issue could come from the city name that has an "é" but then I had a look at the code and saw that it was using yahooapis.com which has been killed in 2017 apparently.

I'm very new to python so I can barely read what the script does. Is there a possibility to set the location manually ? Or to use something like openweathermap ? With possibly manual input to improve accuracy when using a pi that doesn't travel much.

Thank you very much for the examples provided with the pHAT and also for your time

**Comment by Gadgetoid** [comment]
We will indeed have to rewrite this example- weather APIs keep disappearing under our nose and while we knew about this one, I didn't recall we had a Scroll pHAT example using it. Whoops.

Anyway this example would have to be updated either to - as you suggest - OpenWeatherMap or possibly DarkSky.net.

I'm not sure I'll squeeze this in this week, but we already have implementatiosn for both of these services that should be easy enough to port over when I get around to it:

- OpenWeatherMap - https://github.com/pimoroni/blinkt/blob/master/examples/blinkt_thermo.py
- DarkSky - https://github.com/pimoroni/breakout-garden/blob/master/examples/weather/weather.py

**Comment by Gadgetoid** [comment]
See updated code in 77c1625b9ffe564cfb19baf1a216c4a34634ce82

**Comment by eskiiom** [comment]
Hello and thank you very much for such a prompt modification to the code.
I am sorry I didn't give you a proper feedback, this has been a quite corona-busy week !
I gave it a quick try and had a lot of errors with dependencies, especially with bs4 module. Would you please advice if this is a dev package that I need to install ?
Again than you very much

**Comment by Gadgetoid** [comment]
I think you can `sudo apt install python3-bs4` (or `python-bs4` if you're still using 2.x) and it should avoid any issues that might be had with installing/building via pip.
